### ISSUE TITLE
Site crashes when clicking on "Catalogue"

### ISSUE THREAD

**Issue by ChaseC99** [icssc-projects/peterportal-client#129]
If you are on /search/professors and click on "Catalogue", the site crashes.
`TypeError: Cannot read properties of undefined (reading 'forEach')`

![pp_bug](https://user-images.githubusercontent.com/29494270/153162460-37c91e05-ab4f-4bdc-b891-fed242a9ba3f.gif)

**Comment by chenaaron3** [comment]
Thanks for spotting this! Fixed with some routing reconfiguration.
