### ISSUE TITLE
Icons in Preview don't show up

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-client#131]
Seeing the previously taught courses for a professor, as well as the professors for a course, the icons for going left and right, are just squares. Also, I don't know if it's intended, but it's blocking the rating.

![image](https://user-images.githubusercontent.com/9029237/153275633-734542bd-17b8-422d-913a-285d8431a8a9.png)

**Comment by chenaaron3** [comment]
Turns out we had to manually import a font to get the arrows. I think its ok for the left arrow to be blocking the rating because the user has already scrolled past that block. I'm not sure where else to place the arrows
