### ISSUE TITLE
Cannot view grade percentage

### ISSUE THREAD

**Issue by patrickanguyen** [icssc-projects/peterportal-client#172]
I cannot view the grade percentage when I mouse over the graph. Since the words are the same color as the graph. Maybe make the color of the text black or something to make it clearer. 

![image](https://user-images.githubusercontent.com/41417417/155083006-4cf4a089-38e6-43bb-9741-d05372211ef1.png)

**Comment by jxsusilo** [comment]
I'll work on this!
