### ISSUE TITLE
Roadmap Dragging Animation is Disjointed

### ISSUE THREAD

**Issue by patrickanguyen** [icssc-projects/peterportal-client#173]
When dragging a class to a quarter, the class appears over the Quarter name for half-second, then moves to the appropriate place. 

If you would fix this, that would be great :slightly_smiling_face:  because this is bothering me 

![peter](https://user-images.githubusercontent.com/41417417/155087329-d5bdbb86-6845-4300-a43b-bb831a90fb58.gif)

**Comment by chenaaron3** [comment]
Anything for you patty
