### ISSUE TITLE
Connect React's Review Component to Express API

### ISSUE THREAD

**Issue by chenaaron3** [icssc-projects/peterportal-client#18]
### Goal
Integrate the Reviews API into React. Don't start until the pull request #19 is approved. Ask Mars for a FAUNA_SECRET, then add an additional entry to api/.env (FAUNA_SECRET=). I recommend you play around with the endpoints in [Postman](https://www.postman.com/downloads/). Make some dummy data first and get familiar with the endpoints. 
Fauna extension: https://docs.fauna.com/fauna/current/integrations/vs_code.html

### Get Review
- Endpoint URL: /reviews
- Method: GET
- Query: to filter reviews, use one of the below query parameters. To get all reviews, do not provide any query parameters.
1. courseID: String
2. professorID: String
3. userID: String
- [x] Replace dummy data with data from our database using the get review endpoint. 

### Post Review
- Endpoint URL: /reviews
- Method: POST
- Body: key names must be the same
{
    professorID: String
    courseID: String
    userID: String
    reviewContent: String
    rating: Float
    difficulty: Float
    timestamp: String
    gradeReceived: String
    forCredit: Boolean
    score: Int
}
- [ ] When user submits review form in client, send fetch request to update database using the post review endpoint.
- Update: approve the pull request #28 to get access to professor endpoint. 
- use the endpoints courses/api/:courseID and professors/api/:ucinetid

### Vote Review
- Enpoint URL: /reviews/vote
- Method: PATCH
- Body: 
{
    id: String // a review's id is included in the get review endpoint
    upvote: Boolean // true if is an upvote request, false if is a downvote request
}
- [x] When user upvotes or downvotes a review, update the database using the vote review endpoint.

**Comment by xuanbvu** [comment]
<img width="210" alt="Screen Shot 2021-02-06 at 02 30 22" src="https://user-images.githubusercontent.com/17202423/107115708-58545d00-6823-11eb-8b68-a746696b5937.png">
The CSS/color scheme only accounts for integers 1-5 right now, so I'm going to change it to apply to decimals and number greater than 5 by doing:
- flooring decimal numbers
- having the same colors for intervals of 2 (1 and 2 will have the same color, 3 and 4, ... all the way to 9 and 10)

Let me know if the design team has any specific way they want it done!

**Comment by xuanbvu** [comment]
I used `professorID` for the "Taken With" and right now "Quarter Taken" is blank

**Comment by xuanbvu** [comment]
Also for the POST request, do you want me to make the review form component first and then call the request from that component?

**Comment by chenaaron3** [comment]
> <img alt="Screen Shot 2021-02-06 at 02 30 22" width="210" src="https://user-images.githubusercontent.com/17202423/107115708-58545d00-6823-11eb-8b68-a746696b5937.png">
> 
> The CSS/color scheme only accounts for integers 1-5 right now, so I'm going to change it to apply to decimals and number greater than 5 by doing:
> * flooring decimal numbers
> * having the same colors for intervals of 2 (1 and 2 will have the same color, 3 and 4, ... all the way to 9 and 10)
> 
> Let me know if the design team has any specific way they want it done!

These design decisions sound good to me! We can go through with this for now.

**Comment by chenaaron3** [comment]
> I used `professorID` for the "Taken With" and right now "Quarter Taken" is blank
> <img alt="Screen Shot 2021-02-06 at 03 00 34" width="757" src="https://user-images.githubusercontent.com/17202423/107116369-7e7bfc00-6827-11eb-992a-886653bd574e.png">

That's my bad. I'll try to add a quarter taken field soon.

**Comment by chenaaron3** [comment]
> Also for the POST request, do you want me to make the review form component first and then call the request from that component?

Yes, make a form component first, and then make the request when the user submits the data.

**Comment by xuanbvu** [comment]
> > I used `professorID` for the "Taken With" and right now "Quarter Taken" is blank
> > <img alt="Screen Shot 2021-02-06 at 03 00 34" width="757" src="https://user-images.githubusercontent.com/17202423/107116369-7e7bfc00-6827-11eb-992a-886653bd574e.png">
> 
> That's my bad. I'll try to add a quarter taken field soon.
> 
> Edit: just updated the schema to include a 'quarter' field. The code is updated in the master branch.

Ok just saw the edit, thank you!
