### ISSUE TITLE
Scroll on new page

### ISSUE THREAD

**Issue by chenaaron3** [icssc-projects/peterportal-client#37]
![image](https://user-images.githubusercontent.com/44650208/109454240-9f8bd300-7a08-11eb-9c6a-69a911c1fa96.png)

Currently, when you go to a new page index (Page1 => Page2) in the Search Page, it doesn't scroll back to the top of the page. The user has to manually scroll up which is annoying.

**Comment by ashwindevx** [comment]
Can I work on this?
