### ISSUE TITLE
Create Admin Page

### ISSUE THREAD

**Issue by chenaaron3** [icssc-projects/peterportal-client#48]
Allow authorized users to remove flagged comments.
- [x] Get familiar with [retool](https://retool.com/) to create admin page.

**Comment by Kumar85** [comment]
You could use JWT `JSON WebToken` . It's Secure and easy

**Comment by chenaaron3** [comment]
Hey Sakshi, I just finished migrating our database from Fauna to MongoDB. You can find the connection string for mongo at the .env file in the Discord channel.
