### ISSUE TITLE
Implement GET and POST endpoint for Review

### ISSUE THREAD

**Issue by uci-mars** [icssc-projects/peterportal-client#6]
- [x] Connect to main FaunaDB either via the VS Code extension (https://docs.fauna.com/fauna/current/integrations/vs_code) or using the fauna-shell (https://docs.fauna.com/fauna/current/integrations/shell/)

> Ask Mars for an API key, when you're ready

- [x] Create a collection for Reviews

- [x] Create an endpoint on the internal API to POST documents to the FaunaDB Reviews collection using form data.

Schema:
{
  professorID: '...',
  courseID: '...',
  userID: '...',
  reviewContent: '...',
  rating: '...',
  difficulty: '...',
  timestamp: '...',
  gradeReceived: '...',
  forCredit: true|false,
  score: '...'
}

- [x] Create separate indexes on FaunaDB Reviews collection to query by `courseID`, `professorID`, and `userID` 

- [x] Create an index to query all Reviews 

- [x] Create an endpoint on the internal API to GET/query FaunaDB for reviews by courseID and professorID.

- [x] Create endpoints on the internal API to PATCH/modify existing reviews. (Let's just do this for upvote/downvote score for now 😄 )

### Additional Comment

There are two methods to drive FaunaDB. FQL and GraphQL. I would recommend you look into GraphQL because a lot of jobs these days are looking for GraphQL skill. But the choice is up to you! 😉 

Also, try to play with FaunaDB on your personal account first. It can be a lil bit tricky at first, but the Dashboard GUI can be mighty helpful/

**Comment by chenaaron3** [comment]
Finishe
